import Head from 'next/head'
import { HeroSection } from '../sections/HeroSection'
import Hobbies from '../sections/Hobbies'
import { Skills } from '../sections/Skills'
import { Projects } from '../sections/Projects'
import { Contact } from '../sections/Contact'
import { Footer } from '../components/Footer'

export default function Home() {
  return (
    <div>

      <Head>
        <title>HtooHtet | Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/code.png" />
      </Head>

      <HeroSection/>
      <Hobbies/>
      <Projects/>
      <Skills/>
      <Contact/>
      <Footer/>

    </div>
  )
}
